# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"

  config.vm.provision "chef_zero" do |chef|
    chef.cookbooks_path = "../cookbooks"
    chef.add_recipe "nginx"
    chef.add_recipe "sudo"
  end

  config.vm.provision :shell, path: "test_nginx.sh"

end
